### ISSUE TITLE
Feature request: Support for My Mixes (etc.)

### ISSUE THREAD

**Issue by BlackLight** [tamland/python-tidal#100] opened 2022-05-23 15:27 UTC
I've noticed that Tidal populates the Mixes For You collection (as well as Radio Stations/Suggested Albums etc.) through the `https://listen.tidal.com/v1/pages/home` endpoint. The returned format looks like:

```json
{
  "rows": [
    {
      "type": "MIX_LIST",
      "title": "Mixes For You",
      "pagedList": {
        "limit": 10,
        "offset": 0,
        "items": [
          "id": "some-playlist-id",
          "mixType": "DAILY_MIX"
        ]
      }
    }
  ]
}
```

It looks like a low-hanging fruit to add? If 0.7.x is already workable I can also allocate some time for a PR.

**Comment by morguldir** [comment] 2022-06-28 05:47
This should be available now in the 0.7.x branch

Closing as duplicate of #62

**Closed by morguldir** 2022-06-28 05:47 UTC
Labels: duplicate
