### ISSUE TITLE
Support for 24bit 192kHz

### ISSUE THREAD

**Issue by alexandru0-dev** [tamland/python-tidal#188] opened 2023-08-24 15:33 UTC
At the moment the files are only streaming at 24bit 48kHz instead of the 192kHz expected

**Comment by jozefKruszynski** [comment] 2023-09-07 15:59
At the moment, Tidal only allows it's own apps to use the HiRes Flac files higher than 24bit 48kHz

**Comment by alexandru0-dev** [comment] 2023-09-29 11:26
@jozefKruszynski  with tidal-dl i could get 192hz flac files with my personal jwt token that i got from the desktop app on windows

**Comment by RDeluxe** [comment] 2023-10-20 23:00
I can confirm that using the token provided by a native app (MacOS in my case) downloads a much bigger file (tested on https://tidal.com/browse/track/542179)

With a normal token, I get a 48Khz 24 bits file, around 75Mb.
With a native token, the file is uncrypted but weights 217Mb.

Once decrypted:

```
ffprobe -hide_banner Rosanna.flac 
Input #0, flac, from 'Rosanna.flac':
  Duration: 00:05:30.94, start: 0.000000, bitrate: 5256 kb/s
  Stream #0:0: Audio: flac, 192000 Hz, stereo, s32 (24 bit)
```

Don't know if this helps, but always good to know.

**Comment by exislow** [comment] 2024-01-14 18:23
Where can you find your personal TIDAL JWT on a Mac?

**Comment by tehkillerbee** [comment] 2024-01-15 07:40
Closing this issue, as tidal only allows official apps to use high res / 24bit 192kHz bitrates.

**Comment by exislow** [comment] 2024-01-15 07:57
You are closing this without even trying to properly reverse engineering this? I would like to help here.

**Comment by tehkillerbee** [comment] 2024-01-15 08:22
@exislow Playback should be possible as long as you use the correct token, as stated in the previous comments. I have not tested this myself as I do not currently have a subscription with high res.

We cannot assist you with how to get hold of these tokens. I am currently looking into using pkce authentication, as used by the android app. This should also allow us to use high res playback.

**Comment by RDeluxe** [comment] 2024-01-15 09:25
I'm using a network tool to check the API calls from the native app, and getting my token and refresh from there.

With the correct deviceId and refresh token, you should be able to refresh the token correctly, allowing for hi-res download (I tested this a little tool, it does work).

**Comment by exislow** [comment] 2024-01-15 10:04
> @exislow Playback should be possible as long as you use the correct token, as stated in the previous comments. I have not tested this myself as I do not currently have a subscription with high res.
> 
> Sorry, we cannot assist you with how to get hold of these tokens for obvious reasons.
> 
> I am currently looking into using pkce authentication, as used by the android app. This should allow us to use high res playback in the future, since using the device code link login method will not work.

That's a bummer but thank you for sharing your knowledge. I will do some analysis there as well.



> I'm using a network tool to check the API calls from the native app, and getting my token and refreshToken from there.
> 
> With the correct `deviceId` and `refreshToken`, you should be able to refresh the token correctly, allowing for hi-res download (I tested this a little tool, it does work).

So, you are basically using Wireshark / Burp for traffic analysis / interception. I thought somebody figured out where the electron app saves the token.

Btw... After decompilation of the desktop electron app (asar package) I miss the electron backend code files. Only the frontend files are available. But I cannot figure out where the code file are who are handling the IPC calls from the frontend. Does anybody has hint on that?

**Comment by tehkillerbee** [comment] 2024-01-15 10:24
Reopening.

FYI, the Kodi Tidal plugin (containing an old fork of tidalapi) already has support for this, including obtaining tokens from the android apps and using PKCE login: https://github.com/arnesongit/plugin.audio.tidal2

My plan is to port these features to tidalapi

**Comment by exislow** [comment] 2024-01-15 10:57
This sounds great. Amazing, that the already implemented this (https://github.com/arnesongit/plugin.audio.tidal2/blob/e9429d601d0c303d775d05a19a66415b57479d87/resources/lib/tidal2/tidalapi/__init__.py#L86).

Do you need help with porting their code? What is your timeline for that?

**Comment by tehkillerbee** [comment] 2024-01-15 11:42
Exactly. There are many very nice advanced features in this plugin that are yet to be ported to tidalapi, including all the PKCE login and high res playback that was added a couple of months ago. I think most of the legwork has already been done by arnesongit.

I was hoping to port it one of the next couple of months before the next tidalapi release, if I have time aside from work. But you are very welcome to help, PRs are always welcome. Just give me a heads-up if you start working on it :+1:

**Comment by exislow** [comment] 2024-01-19 17:57
@tehkillerbee: I have started working on the PKCE port. First PoC seems to work. As soon as I have something really suitable for testing I will inform you. Would be great, if we could align on code style and tests later.

**Comment by exislow** [comment] 2024-01-19 18:09
Hell yeah, it works! I can download Hi Res FLAC files: https://github.com/exislow/python-tidal/commit/6f031a0cdb2c8293f2b2b26da68497b809611d87

```
$ afinfo The\ Doobie\ Brothers\ -\ Listen\ to\ the\ Music\ \(2016\ Remaster\).mp4 
File:          The Doobie Brothers - Listen to the Music (2016 Remaster).mp4
File type ID:   mp4fLine.flac                                                                                                                     
Num Tracks:     1
----
Data format:     2 ch, 192000 Hz, flac (0x00000003) from 24-bit source, 4096 frames/packet
                no channel layout.
estimated duration: 288.021333 sec
audio bytes: 195354502
audio packets: 13501
bit rate: 5426112 bits per second
packet size upper bound: 16164
maximum packet size: 16164
audio data file offset: 219697
not optimized
----

```

**Comment by GioF71** [comment] 2024-01-19 18:31
That is amazing news :-)

**Comment by jozefKruszynski** [comment] 2024-01-19 20:01
A question here would be how to handle the client_id. 
I believe that the Kodi plugin extracts it from a given APK as part of the setup process and I would urge against storing it in the repo. I would also urge against adding the same extraction process to the repo here.
However this then assumes a level of knowledge and technical competency in order for a user to extract the required values.

**Comment by tehkillerbee** [comment] 2024-01-19 20:08
@exislow @jozefKruszynski As Jozef mentioned, storing the client_id is a no-go.

Including the utilities to extract it from the APK and/or including the instructions to obtain it will also be a bad idea IMO.

**Comment by exislow** [comment] 2024-01-20 09:31
Can you tell me, why this is a no go? It is already done the same way right now, see https://github.com/tamland/python-tidal/blob/master/tidalapi/session.py#L167
If you like, we can obfuscate this using base64 encoding or what so ever.

Getting the permission is great but we do not need it, since a) their code is under GPL (https://github.com/arnesongit/plugin.audio.tidal2/blob/master/LICENSE.txt) and b) anyway I would fully re-write the code to properply integrate it into this library.

The extraction process of the client id strings is very easy:

1. Get the TIDAL apk.
2. Decompile it with, for instance, https://github.com/ax/apk.sh
3. Check `assets/dexopt/secrets.properties`

I kinda do not really get the trouble here. Maybe somebody explain to me what actual issues we are facing / what is right now knew compared to the already existing ways this API is accessing TIDAL.

**Comment by tehkillerbee** [comment] 2024-01-20 10:17
@exislow

 Including a non-obfuscated id will quickly get noticed and it will stop working. Hence the reason that is why we do not do it like that right now. Otherwise, we have to keep updating the ids, each time they get taken down.

Including an id with highres support will most likely cause this project to get taken down by Tidal, once and for all, as it will make it too easy to download HiRes music directly from tidal. So I still think the only way forward is to allow the user to input the id that he/she has obtained manually *somehow*.

**Comment by jozefKruszynski** [comment] 2024-01-20 11:13
Now if only Tidal would get a move on and release their public api with all these features included, and we could build against that instead.

**Comment by tehkillerbee** [comment] 2024-01-20 11:31
Agreed, or provide us with a rate limited client id similar to the official api. That should at least help mitigating misuse (batch downloads etc)

**Comment by exislow** [comment] 2024-01-20 13:44
Why should tidal take this down immediately, if we base64 encode the client is, if they haven’t done it so far. It is already like this in the code. We only would replace / extend the current client id. This doesn’t make sense to me…

Regarding the API discussion: WTF? I don’t think tidal likes it, if we store their music instead of immediately deleting it after listening (which is called streaming). You are mad men :D

@tehkillerbee / @tamland: I do not really want to have super super long discussions about fictional possibilities which can happen, if we replace / extend the already in the code present client id. I would like to get this done ASAP and continue to spent my free time on something else. My proposal is to store the new client id the same way (as already done by this project), since nothing happened so far. What is your opinion on this? Do you have a better solution? I am not voting for a solution, where a user needs to extract the client is by themself. If this is what you are voting for I would fork this code and create a new library called `tidal-api-ng` which has the client id present. Let me know your thoughts.

**Comment by jozefKruszynski** [comment] 2024-01-20 13:51
> Why should tidal take this down immediately, if we base64 encode the client is, if they haven’t done it so far. It is already like this in the code. We only would replace / extend the current client id. This doesn’t make sense to me…
> 
> 
> 
> Regarding the API discussion: WTF? I don’t think tidal likes it, if we store their music instead of immediately deleting it after listening (which is called streaming). You are mad men :D
> 
> 
> 
> @tehkillerbee / @tamland: I do not really want to have super super long discussions about fictional possibilities which can happen, if we replace / extend the already in the code present client id. I would like to get this done ASAP and continue to spent my free time on something else. My proposal is to store the new client id the same way (as already done by this project), since nothing happened so far. What is your opinion on this? Do you have a better solution? I am not voting for a solution, where a user needs to extract the client is by themself. If this is what you are voting for I would fork this code and create a new library called `tidal-api-ng` which has the client id present. Let me know your thoughts.  

This library here is created for streaming. I don't know what you mean about downloading stuff long term, I guess you're doing that some other way.

**Comment by jozefKruszynski** [comment] 2024-01-20 14:50
> Why should tidal take this down immediately, if we base64 encode the client is, if they haven’t done it so far. It is already like this in the code. We only would replace / extend the current client id. This doesn’t make sense to me…
> 
> Regarding the API discussion: WTF? I don’t think tidal likes it, if we store their music instead of immediately deleting it after listening (which is called streaming). You are mad men :D
> 
> @tehkillerbee / @tamland: I do not really want to have super super long discussions about fictional possibilities which can happen, if we replace / extend the already in the code present client id. I would like to get this done ASAP and continue to spent my free time on something else. My proposal is to store the new client id the same way (as already done by this project), since nothing happened so far. What is your opinion on this? Do you have a better solution? I am not voting for a solution, where a user needs to extract the client is by themself. If this is what you are voting for I would fork this code and create a new library called `tidal-api-ng` which has the client id present. Let me know your thoughts.

To be fair, I understand exactly where you are coming from, you're right about the project already containing an obfuscated client_id. I think the point that both myself, and @tehkillerbee were trying to make is that actually that probably never should have happened in the history of the project.

In the end, I just want to say thank you for putting in the work that you have done so far. Please do not see my comments thus far as anything but simple musings on the grey area that this project skirts in.

**Comment by tehkillerbee** [comment] 2024-01-22 17:17
@exislow Its not ideal but if the (obfuscated) client_id should be added for high-res playback, I prefer that we add it as an additional `client_id` that will be used when high-res mode is requested by the user. So in this case we have the original id to fall back on, in case the one obtained from the apk gets rotated and/or stops working.

In any case, thank you for your contribution. PRs are always very appreciated and proper high-res playback has been one of the big tasks that I'd been wanting for a long time. It would be nice to finally add it to the next release of tidalapi.

By the way, @tamland is not maintaining this project anymore but you should be able to reach out to other contributors and maintainers such as myself if you have questions.

**Comment by exislow** [comment] 2024-01-22 19:48
@tehkillerbee: I agree to your suggestion and will get you a PR with a second obfuscated client id. But keep in mind, that the current client id was also extracted from an APK by someone and can be rotated as well. But client id rotation is very unlikely, since all users would be forced to update the app otherwise it wouldn't work from one day to another -- just saying. But of course this can happen.

**Comment by exislow** [comment] 2024-01-23 08:21
@tehkillerbee: I would love to get comments / PR acceptance for this https://github.com/tamland/python-tidal/pull/221

**Closed** 2024-01-27 16:00 UTC
