### ISSUE TITLE
How get now playing track?

### ISSUE THREAD

**Issue by whypodg** [tamland/python-tidal#124] opened 2023-01-05 09:49 UTC
I want to try to get now playing track, but I can't find such a method/function
How to do it and is it possible at all?

**Comment by bjesus** [comment] 2023-01-27 18:45
Duplicate of https://github.com/tamland/python-tidal/issues/20

**Comment by tehkillerbee** [comment] 2023-05-22 20:05
Closing as duplicate

**Closed by tehkillerbee** 2023-05-22 20:05 UTC
