### ISSUE TITLE
Is there a way to get the current playing song?

### ISSUE THREAD

**Issue by YasherK** [tamland/python-tidal#61] opened 2021-03-04 02:48 UTC
I'm looking for a way to modify playlists, and play and pause songs. If that's possible I would appreciate if someone demonstrated how. I couldn't find it in the API.

**Comment by morguldir** [comment] 2022-06-28 05:34
Not really possible, you can make your own player that can do anything you want though.

Playlist modification is available in 0.7.x branch, documentation might be a bit lacking though, but will probably complete that soon. [create_playlist()](https://0-7-x--tidalapi.netlify.app/api.html#tidalapi.user.LoggedInUser.create_playlist), and [UserPlaylist](https://0-7-x--tidalapi.netlify.app/api.html#tidalapi.playlist.UserPlaylist), which can be edited

Closing as a duplicate of #20 and #23

**Closed by morguldir** 2022-06-28 05:34 UTC
Labels: duplicate
